<h1>サイト登録</h1>
<form class="well" role="search" method="post" action="/admin/origin/insert/">

	<div class="form-group">
		<label>サイト名称</label>
		<input type="text" class="form-control" name="originName" required>
	</div>

	<div class="form-group">
		<label>サイトURL</label>
		<input type="url" class="form-control" name="originUrl" required>
	</div>

	<div class="form-group">
		<label>RSS</label>
		<input type="url" class="form-control" name="originRss" required>
	</div>

	<div class="form-group">
		<label>イメージURL</label>
		<input type="url" class="form-control" name="originImage" required>
	</div>

	<button type="submit" class="btn btn-primary">登録実行</button>

</form>