<h1>サイト一覧</h1>

<table class="table table-striped table-bordered">
	<thead>
	<tr>
		<th>ID</th>
		<th>サイト名</th>
		<th>IN</th>
		<th>OUT</th>
		<th>最終取得</th>
		<th>取得失敗</th>
		<th>状態</th>
		<th>操作</th>
		<th>取消</th>
	</tr>
	</thead>
	<tbody>
	<?php foreach ($this->rowSet as $row) { ?>
		<tr>
			<td><?php echo $row->originCode; ?></td>
			<td><?php echo $row->originName; ?></td>
			<td class="text-right"><?php echo number_format($row->originIn); ?></td>
			<td class="text-right"><?php echo number_format($row->originOut); ?></td>
			<td><?php echo date("Y/m/d H:i", $row->originGetAt); ?></td>
			<td class="text-right"><?php echo number_format($row->originFailure); ?></td>
			<td>
				<?php if ($row->originActive == 0){ ?>
					<a class="btn btn-info btn-xs" href="/admin/origin/active/primary/<?php echo $row->originCode; ?>/">有効化</a>
				<?php } else { ?>
					<a class="btn btn-warning btn-xs" href="/admin/origin/disable/primary/<?php echo $row->originCode; ?>/">無効化</a>
				<?php } ?>
			</td>
			<td>
				<a class="btn btn-primary btn-xs" href="/admin/origin/get/primary/<?php echo $row->originCode; ?>/">詳細画面</a>
			</td>
			<td>
				<a class="btn btn-danger btn-xs" href="/admin/origin/delete/primary/<?php echo $row->originCode; ?>/">削除実行</a>
			</td>
		</tr>
	<?php } ?>
	</tbody>
</table>