<html lang="ja">
<head>
	<meta charset="utf-8" />
	<!-- Latest compiled and minified CSS -->
	<link
		rel="stylesheet"
		href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
		integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
		crossorigin="anonymous">

	<!-- Optional theme -->
	<link
		rel="stylesheet"
		href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
		integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
		crossorigin="anonymous">

	<!-- Latest compiled and minified JavaScript -->
	<script
		src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
		integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
		crossorigin="anonymous">

	</script>
</head>
<body>

<div style="max-width: 600px;margin: auto;">

	<h1>ログイン画面</h1>
	<form class="well" role="search" method="post" action="/admin/login/try/">

		<div class="form-group">
			<label>ユーザー名</label>
			<input type="text" class="form-control" name="username" required>
		</div>

		<div class="form-group">
			<label>パスワード</label>
			<input type="password" class="form-control" name="password" required>
		</div>

		<button type="submit" class="btn btn-primary">ログイン実行</button>

	</form>

</div>

</body>
</html>