<html lang="ja">
<head>
	<meta charset="utf-8" />
	<!-- Latest compiled and minified CSS -->
	<link
		rel="stylesheet"
		href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
		integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
		crossorigin="anonymous">

	<!-- Optional theme -->
	<link
		rel="stylesheet"
		href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
		integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
		crossorigin="anonymous">

	<!-- Latest compiled and minified JavaScript -->
	<script
		src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
		integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
		crossorigin="anonymous">

	</script>
</head>
<body>
	<table style="table-layout: fixed;width: 100%;">
		<tr>
			<td style="width: 200px;padding: 10px;vertical-align: top;">
				<h3>
					MENU
				</h3>
				<div>
					<ul>
						<li>
							<a href="/admin/origin/add/">サイト登録</a>
						</li>
						<li>
							<a href="/admin/origin/">サイト一覧</a>
						</li>
						<li>
							<a href="/admin/archive/">記事一覧</a>
						</li>
						<li>
							<a href="/admin/master/">マスタ設定</a>
						</li>
						<li>
							<a href="/admin/login/logout/">ログアウト</a>
						</li>
					</ul>
				</div>
			</td>
			<td style="padding: 10px;">
				<div style="max-width: 1000px;">
					<?php echo $this->layout()->content; ?>
				</div>
			</td>
		</tr>
	</table>
</body>
</html>