<h1>記事一覧</h1>

<table class="table table-striped table-bordered">
	<thead>
	<tr>
		<th>ID</th>
		<th>記事名</th>
		<th>サイト</th>
		<th>取消</th>
	</tr>
	</thead>
	<tbody>
	<?php foreach ($this->rowSet as $row) { ?>
		<tr>
			<td><?php echo $row->archiveCode; ?></td>
			<td><?php echo $row->archiveTitle; ?></td>
			<td><?php echo $row->originName; ?></td>
			<td>
				<a class="btn btn-danger btn-xs" href="/admin/archive/delete/primary/<?php echo $row->archiveCode; ?>/">削除実行</a>
			</td>
		</tr>
	<?php } ?>
	</tbody>
</table>


<?php
echo $this->partial("pager.phtml", [
	"offset" => Zend_Controller_Front::getInstance()->getRequest()->getParam("offset"),
	"limit" => 100,
	"count" => $this->results
]);
?>
