
<h3>ORIGINS</h3>

<?php foreach ($this->origins as $origin){ ?>

	<div class="col-xs-12 col-md-12 col-lg-6">
		<div class="origin">
			<div class="sitetitle pull-left">
				<a href="/origin/out/originCode/<?php echo $origin->originCode; ?>/" rel="nofollow" target="_blank">
					<?php echo $origin->originName; ?>
				</a>
			</div>
			<div class="pull-right reward" style="">
				IN：<?php echo number_format($origin->originIn); ?> / OUT：<?php echo number_format($origin->originOut); ?>
			</div>
			<div class="clearfix"></div>

			<div class="col-xs-3 image">

				<a href="/origin/out/originCode/<?php echo $origin->originCode; ?>/" target="_blank" rel="nofollow">
					<img src="<?php echo $origin->originImage; ?>" alt="<?php echo $origin->originName; ?>">
				</a>
			</div>

			<div class="col-xs-9">
				<ul class="list-box">
					<?php foreach ($origin->latestArchives() as $archive){ ?>
						<li class="item">
							<a href="/archive/show/<?php echo $archive->archiveCode; ?>/"><?php echo $archive->archiveTitle; ?></a>
						</li>
					<?php } ?>
				</ul>
			</div>
		</div>
	</div>

<?php } ?>